export const SET_LOADING = 'SET_LOADING'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const SET_USER = 'SET_USER'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR'
export const FETCH_SINGLE_JOB_SUCCESS = 'FETCH_SINGLE_JOB_SUCCESS'
export const FETCH_SINGLE_JOB_ERROR = 'FETCH_SINGLE_JOB_ERROR'

export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'


export const FETCH_APPLIES_SUCCESS = 'FETCH_APPLIES_SUCCESS'
export const FETCH_APPLIES_ERROR = 'FETCH_APPLIES_ERROR'

export const CREATE_APPLY_SUCCESS = 'CREATE_APPLY_SUCCESS'
export const CREATE_APPLY_ERROR = 'CREATE_APPLY_ERROR'

export const FETCH_SINGLE_APPLY_SUCCESS = 'FETCH_SINGLE_APPLY_SUCCESS'
export const FETCH_SINGLE_APPLY_ERROR = 'FETCH_SINGLE_APPLY_ERROR'

export const DELETE_APPLY_ERROR = 'DELETE_APPLY_ERROR'

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS'

export const SEND_MAIL_ERROR = 'SEND_MAIL_ERROR'

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'

export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR'

export const GET_FILE_ERROR = 'GET_FILE_ERROR'
export const GET_FILE_SUCCESS = 'GET_FILE_SUCCESS'

export const SEARCH_SUCCESS= 'SEARCH_SUCCESS'
export const SEARCH_FAILURE= 'SEARCH_FAILURE'

export  const FETCH_RECOMMENDED_JOBS_SUCCESS = 'FETCH_RECOMMENDED_JOBS_SUCCESS'
export  const FETCH_RECOMMENDED_JOBS_ERROR = 'FETCH_RECOMMENDED_JOBS_ERROR'