import Register from './Register'
import Home from './Home'
import Dashboard from './Dashboard'
import Edit from './Edit'
import Error from './Error'
import PrivateRoute from './PrivateRoute'
import Apply from './Apply'
import Applies from './Applies'
import SpecificApplies from './SpecificApplies'
import Profile from './Profile'
import Resume from './Resume'
import AddJob from './AddJob'
import JobDetails from './JobDetails'
export { Home, JobDetails, Register,Resume, Dashboard, Edit, Error,AddJob, PrivateRoute,Apply,Applies,SpecificApplies,Profile }
